class Endpoints:

    ESTABLISHMENTS = '/establishments'
    AUTHORIZATION = '/authentication'
    ORDERS = '/orders'
    ORDERS_ITEMS = f'{ORDERS}/items'
    ORDERS_MONITOR = f'{ORDERS}/monitor'
    ORDERS_PAYMENTS = f'{ORDERS}/payments'
    PAYMENTSFORMS = '/payment_forms'
    PRODUCTS = '/products'
    PRODUCTS_ADD_ONES = f'{PRODUCTS}/add_ones'
    PRODUCTS_COMPLEMENTS = f'{PRODUCTS}/complements'
    MANAGE_PRODUCT_IMAGES = f'{PRODUCTS}/images'
    MENUITEMS = f'{PRODUCTS}/menu_items'
    USERS = '/users'
    CATEGORIES = '/categories'
    SESSIONS = '/sessions'
    REPORTS_SALES = '/reports/sales'
    PAYMENTS = '/payments'
    FILES = '/files'
    MENUS = '/menus'
    APPS = '/apps'